### ISSUE TITLE
Some (minor) feedback

### ISSUE THREAD

**Issue by drvinceknight** [Scott3142/Scott3142.github.io#1]
Looks great Scott. Very sharp.

- I really like the collaborators page with the icons
- There is a bit of overlap between pages, your teaching and research for example have some overlap (under key contributions). I'd suggest trying to avoid this, at the very least because at some point you'll change one and not the other.

It looks like hard coded html if I'm not incorrect? You might want to, at some point, take a look at a static site framework which means you won't have to repeat the heading on each page etc... One of the most famous ones is jekyll: https://jekyllrb.com/ (which works out of the box with github pages). @nikoleta-V3 uses that and I used to. 

I now run my own because I wanted a bit more freedom: https://github.com/drvinceknight/drvinceknight.github.com. So all my "data" is in stuff like this: https://github.com/drvinceknight/drvinceknight.github.com/tree/master/src/data/Publication and then I just have a template engine (https://github.com/drvinceknight/drvinceknight.github.com/blob/master/src/main.py) that builds both the html and a latex/pdf version.

I hope that's helpful.

**Comment by Scott3142** [comment]
Thanks for the feedback and advice! 

I had actually looked at Jekyll, in fact the template I adapted was set up to use Jekyll, but I stripped it out and went to hard code HTML simply because I like the freedom. I do like the idea of a template engine though, so I'll have a look into that. The way I've dealt with not repeating headings on sites in the past is to just php include, although I'm guessing github pages doesn't support php... I'll flick through the way you do it anyway, and have another look at Jekyll in case I sort of missed the point of it on my first look! 

Thanks again!
